"""
Generate RGB565 C arrays from emoji characters using Pillow.
Run from the firmware/tools directory:  python gen_icons.py
Output: ../include/icon_data.h
"""

from PIL import Image, ImageDraw, ImageFont
import struct
import os
import sys

ICON_SIZE = 120  # pixels square — fits nicely on 368px wide display
OUTPUT = os.path.join(os.path.dirname(__file__), "../include/icon_data.h")

# Icon set: (id, name, emoji_char, fallback_color)
ICONS = [
    (0, "NONE",     None,  None),          # No icon — text only
    (1, "MEETING",  "🔴",  (220, 38, 38)), # Red circle
    (2, "WFH",      "🏠",  (37, 99, 235)), # House
    (3, "OOF",      "✈️",  (124, 58, 237)), # Plane
    (4, "LUNCH",    "🍕",  (234, 88, 12)), # Pizza
    (5, "FOCUS",    "🎧",  (16, 185, 129)), # Headphones
    (6, "BACK",     "⏰",  (245, 158, 11)), # Clock
    (7, "BUSY",     "🚫",  (239, 68, 68)), # No entry
]

def find_emoji_font(size):
    """Try to find a font that renders emoji."""
    candidates = [
        # Windows
        "C:/Windows/Fonts/seguiemj.ttf",   # Segoe UI Emoji
        "C:/Windows/Fonts/segoeui.ttf",
        # macOS
        "/System/Library/Fonts/Apple Color Emoji.ttc",
        # Linux
        "/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf",
        "/usr/share/fonts/noto/NotoColorEmoji.ttf",
    ]
    for path in candidates:
        if os.path.exists(path):
            try:
                font = ImageFont.truetype(path, size)
                print(f"  Using font: {path}")
                return font
            except Exception as e:
                print(f"  Could not load {path}: {e}")
    return None


def render_emoji(emoji_char, size, fallback_color):
    """Render an emoji to a square RGBA image."""
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)

    if emoji_char:
        font = find_emoji_font(int(size * 0.75))
        if font:
            # Draw centered
            try:
                bbox = draw.textbbox((0, 0), emoji_char, font=font)
                w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
                x = (size - w) // 2 - bbox[0]
                y = (size - h) // 2 - bbox[1]
                draw.text((x, y), emoji_char, font=font, embedded_color=True)
                return img
            except Exception as e:
                print(f"  Text draw failed: {e}")

    # Fallback: colored circle
    color = fallback_color or (128, 128, 128)
    margin = size // 8
    draw.ellipse([margin, margin, size - margin, size - margin],
                 fill=(*color, 255))
    return img


def rgba_to_rgb565(img: Image.Image, bg=(0, 0, 0)) -> bytes:
    """Convert RGBA image to RGB565 little-endian bytes, compositing over bg."""
    rgb = Image.new("RGB", img.size, bg)
    rgb.paste(img, mask=img.split()[3] if img.mode == "RGBA" else None)
    data = bytearray()
    for r, g, b in rgb.getdata():
        r5 = (r >> 3) & 0x1F
        g6 = (g >> 2) & 0x3F
        b5 = (b >> 3) & 0x1F
        val = (r5 << 11) | (g6 << 5) | b5
        data += struct.pack("<H", val)
    return bytes(data)


def array_to_c(name, data, size):
    """Format bytes as a C uint16_t array."""
    words = [struct.unpack("<H", data[i:i+2])[0] for i in range(0, len(data), 2)]
    lines = []
    lines.append(f"// {name} — {size}x{size} RGB565")
    lines.append(f"static const uint16_t ICON_{name}[{size*size}] PROGMEM = {{")
    row_size = 12
    for i in range(0, len(words), row_size):
        chunk = words[i:i+row_size]
        lines.append("    " + ", ".join(f"0x{w:04X}" for w in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    print(f"Generating {len(ICONS)} icons at {ICON_SIZE}x{ICON_SIZE}px...")

    parts = [
        "// icon_data.h — auto-generated by gen_icons.py, do not edit",
        "#pragma once",
        "#include <pgmspace.h>",
        f"#define ICON_SIZE {ICON_SIZE}",
        f"#define ICON_COUNT {len(ICONS)}",
        "",
    ]

    icon_names = []
    for icon_id, name, emoji, fallback in ICONS:
        if emoji is None:
            # NONE icon — all zeros (not used for drawing)
            data = bytes(ICON_SIZE * ICON_SIZE * 2)
        else:
            print(f"  Rendering icon {icon_id}: {name} {emoji or '(fallback)'}")
            img = render_emoji(emoji, ICON_SIZE, fallback)
            data = rgba_to_rgb565(img, bg=(0, 0, 0))

        parts.append(array_to_c(name, data, ICON_SIZE))
        parts.append("")
        icon_names.append(f"ICON_{name}")

    # Lookup table
    parts.append("// Pointer table indexed by icon_id")
    parts.append(f"static const uint16_t* const ICON_TABLE[ICON_COUNT] = {{")
    for name in icon_names:
        parts.append(f"    {name},")
    parts.append("};")

    with open(OUTPUT, "w") as f:
        f.write("\n".join(parts) + "\n")

    print(f"Written to {OUTPUT}")
    size_kb = os.path.getsize(OUTPUT) / 1024
    flash_kb = len(ICONS) * ICON_SIZE * ICON_SIZE * 2 / 1024
    print(f"  Header size: {size_kb:.1f} KB, Flash usage: {flash_kb:.1f} KB")


if __name__ == "__main__":
    main()
