"""
Generate pre-compiled preset state images as JPEG C byte arrays.
Run from the repo root:  python firmware/tools/gen_preset_images.py
Output: firmware/include/preset_images.h

Uses the service's render_screen() so firmware images are pixel-identical
to what the service sends over BLE.
"""

import os
import sys

# Add service/src to path so we can import image_processor directly
repo_root = os.path.join(os.path.dirname(__file__), "..", "..", "service", "src")
sys.path.insert(0, os.path.abspath(repo_root))

from image_processor import render_screen

OUTPUT = os.path.join(os.path.dirname(__file__), "../include/preset_images.h")

# Must match _PRESET_CONFIG in service/src/ble_client.py
PRESETS = [
    ("IN_MEETING", "🔴", "In a\nMeeting",      200, 20,  20),
    ("WFH",        "🏠", "Working\nFrom Home",   10, 30, 120),
    ("OOF",        "✈️", "Out of\nOffice",       60,  0, 120),
    ("AVAILABLE",  "☀️", "Available",           140, 90,   0),
]


def to_c_array(name: str, data: bytes) -> str:
    lines = [
        f"#define PRESET_{name}_LEN {len(data)}",
        f"static const uint8_t PRESET_{name}_DATA[{len(data)}] PROGMEM = {{",
    ]
    row = 16
    for i in range(0, len(data), row):
        chunk = data[i:i + row]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    parts = [
        "// preset_images.h — auto-generated by gen_preset_images.py, do not edit",
        "#pragma once",
        "#include <pgmspace.h>",
        "",
    ]

    for name, emoji, text, bg_r, bg_g, bg_b in PRESETS:
        print(f"  Rendering {name}...")
        jpeg = render_screen(emoji=emoji, text=text,
                             bg_r=bg_r, bg_g=bg_g, bg_b=bg_b)
        print(f"    {len(jpeg):,} bytes ({len(jpeg)/1024:.1f} KB)")
        parts.append(to_c_array(name, jpeg))
        parts.append("")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w") as f:
        f.write("\n".join(parts) + "\n")
    print(f"Written to {OUTPUT}")


if __name__ == "__main__":
    main()
