"""
Generate the boot splash screen as a JPEG C byte array.
Run from the firmware/tools directory:  python gen_boot_splash.py
Output: ../include/boot_splash.h

Renders a 368x448 full-screen JPEG of the Meeting Light logo (💡 + "Meeting Light")
using Pillow, then wraps it as a C uint8_t array for direct use with display_show_image().
"""

import os
import sys
import struct

# Allow importing from the service if run from repo root, but don't require it.
# This script is self-contained using Pillow directly.
from PIL import Image, ImageDraw, ImageFont

SCREEN_W = 368
SCREEN_H = 448
JPEG_QUALITY = 80
OUTPUT = os.path.join(os.path.dirname(__file__), "../include/boot_splash.h")

BG_COLOR   = (15, 15, 25)   # near-black dark navy
TEXT_COLOR = (230, 230, 230) # off-white


def find_emoji_font(size):
    candidates = [
        "C:/Windows/Fonts/seguiemj.ttf",
        "C:/Windows/Fonts/segoeui.ttf",
        "/System/Library/Fonts/Apple Color Emoji.ttc",
        "/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf",
        "/usr/share/fonts/noto/NotoColorEmoji.ttf",
    ]
    for path in candidates:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
    return None


def find_text_font(size):
    candidates = [
        "C:/Windows/Fonts/segoeui.ttf",
        "C:/Windows/Fonts/arial.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for path in candidates:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
    return ImageFont.load_default()


def render_splash() -> bytes:
    img = Image.new("RGB", (SCREEN_W, SCREEN_H), BG_COLOR)
    draw = ImageDraw.Draw(img)

    emoji = "💡"
    title = "Meeting Light"

    # Emoji — large, upper portion
    emoji_size = int(SCREEN_H * 0.32)
    emoji_font = find_emoji_font(emoji_size)
    title_size = 44
    title_font = find_text_font(title_size)

    gap       = int(SCREEN_H * 0.04)   # space between emoji and text
    group_h   = emoji_size + gap + title_size

    y = (SCREEN_H - group_h) // 2      # vertically center the whole group

    # Draw emoji
    if emoji_font:
        # Strip variation selector for bbox measurement
        measure_emoji = emoji.replace("️", "")
        try:
            bbox = draw.textbbox((0, 0), measure_emoji, font=emoji_font)
        except Exception:
            bbox = (0, 0, emoji_size, emoji_size)
        ew = bbox[2] - bbox[0]
        ex = (SCREEN_W - ew) // 2 - bbox[0]
        draw.text((ex, y - bbox[1]), emoji, font=emoji_font, embedded_color=True)
    else:
        # Fallback: yellow circle
        r = emoji_size // 2
        cx = SCREEN_W // 2
        draw.ellipse([cx - r, y, cx + r, y + emoji_size], fill=(255, 220, 0))

    y += emoji_size + gap

    # Draw title text
    try:
        bbox = draw.textbbox((0, 0), title, font=title_font)
        tw = bbox[2] - bbox[0]
        tx = (SCREEN_W - tw) // 2 - bbox[0]
        draw.text((tx, y - bbox[1]), title, font=title_font, fill=TEXT_COLOR)
    except Exception:
        draw.text((SCREEN_W // 4, y), title, fill=TEXT_COLOR)

    # Encode to JPEG
    import io
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=JPEG_QUALITY, optimize=True)
    return buf.getvalue()


def to_c_array(data: bytes, name: str) -> str:
    lines = [
        f"// {name} — auto-generated by gen_boot_splash.py, do not edit",
        "#pragma once",
        "#include <pgmspace.h>",
        f"#define BOOT_SPLASH_LEN {len(data)}",
        f"static const uint8_t BOOT_SPLASH_DATA[{len(data)}] PROGMEM = {{",
    ]
    row = 16
    for i in range(0, len(data), row):
        chunk = data[i:i + row]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    print("Rendering boot splash...")
    jpeg_data = render_splash()
    print(f"  JPEG size: {len(jpeg_data):,} bytes ({len(jpeg_data)/1024:.1f} KB)")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    c_src = to_c_array(jpeg_data, "boot_splash")
    with open(OUTPUT, "w") as f:
        f.write(c_src)
    print(f"  Written to {OUTPUT}")


if __name__ == "__main__":
    main()
