[env:esp32c6]
; pioarduino fork required for ESP32-C6 + Arduino framework support
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    moononournation/GFX Library for Arduino@^1.5.6
    lewisxhe/XPowersLib@^0.2.7
    h2zero/NimBLE-Arduino@^2.1.2

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM=0
    -DLCD_WIDTH=368
    -DLCD_HEIGHT=448
    -DLCD_QSPI_FREQ=40000000
